travis:
  secure:
    BINSTAR_TOKEN: JGZtpXU51G5a2TWjyyly8EFy06qw94ieImX8r1zmWtXxXV2V7mZOYPMLBu4LC+FSuWqsw2/UqXtolNqKzmNVbRV/7IjU2C6XSEnLU6kuIYdZUrPATx4Y+7jzQ0arrwEXwl9rCY2r7jNMtTBYB5bIhc4htREHUjIoMCLScBMx6EXolZdf+HwqnUEzkn3LleCLvH+cy3KWlmPtmqiik6Lq+X4liTCkouGSVygPL61WOpPwIMyL6BaU1aiZBGKAMWSPfSKF7HiOa0xW73bbcFxn7NkwHV/TC9dn1Exw5d5Idnb+I4DKYMhsv2NsjPp74bgssLz/uQQIHI9qTpCzSKOlc8NGc8NqcYazujgUK4JccZvJMeg15mgYd4s/uQ4Qqbb08hXfUVJRYu515nmJZocdqaLn/wvVWfOxyi+6SK3/BFAosI2EPixcItOpNV/mksfvu3UMytBEqq+CLESO//SdE/yhXjQk0GcNvcaD6Oiylx7go7J94hSPvLeuQrcrHj/JG/1u+ndXgNlz8Mlk5U3aYk9V/e4hUH6I8Teiq+PzKZHJ3mTKX5JEJbvnyvZA+CPZGUIbH40evWuEeFs+gGA9vUOGZWyEtzd6S9RwPwWhSqWcTbrAet0h5+a7AtjuUw+/B0t/c8WNoAyzZYFvRxE2/rjbJVeFZtZUBHSrsQERmB8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
